minecraft_directory = 'C:\Users\Tsutomu\AppData\Local\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState\games\com.mojang\minecraftWorlds'
backup_path = '\\NASYTM1\Backup\minecraft_backup'
wait_time = 300

